spring:
  profiles:
    active: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: auth-api

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true

  info:
    env:
      enabled: true

server:
  shutdown: graceful

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refresh-expiration-time: 259200000 # 3days
  access-expiration-time: 3600000 # 1hour

