name: CI/CD Pipeline for Spring Boot Auth Api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run SonarQube analysis
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=triple-seven-auth-api \
          -Dsonar.projectName='triple-seven-auth-api' \
          -Dsonar.host.url=http://133.186.241.167:9000 \
          -Dsonar.token=sqp_34dace0d3275c90d922f83494f8ea7ff9043c1d2